################################# Default configuration ###################
baseURL = "/"
title = "Goldschmiede Goldspecht"
theme = "meghna-hugo"
themesDir = "./themes"

# post pagination
paginate = "6"

# post excerpt
summaryLength = "15"

# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com

# disable language
disableLanguages = []
defaultContentLanguage = "de"

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
# [[params.plugins.css]]
# link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
# [[params.plugins.js]]
# link = "plugins/google-map/map.js"

################### German Navigation ########################

[[Languages.de.menu.main]]
name = "Leistungen"
url = "#services"
weight = 1

[[Languages.de.menu.main]]
name = "Shop"
url = "#shop"
weight = 2

[[Languages.de.menu.main]]
name = "Kontakt"
url = "#contact"
weight = 3

[[Languages.de.menu.main]]
name = "Trauringkonfigurator"
url = "#cta"
weight = 4

[[Languages.de.menu.main]]
name = "Galerie"
url = "#portfolio"
weight = 5

# [[Languages.de.menu.main]]
# name = "Neues"
# url = "#blog"
# weight = 40

[[Languages.de.menu.policy]]
name = "Datenschutzerklärung"
url = "/datenschutz"
weight = 10

[[Languages.de.menu.policy]]
name = "Impressum"
url = "/impressum"
weight = 20

################### English Navigation ########################

# [[Languages.en.menu.main]]
# name = "About me"
# url = "#feature"
# weight = 1
# 
# [[Languages.en.menu.main]]
# name = "News"
# url = "#blog"
# weight = 3
# 
# [[Languages.en.menu.main]]
# name = "Gallery"
# url = "#portfolio"
# weight = 2
# 
# [[Languages.en.menu.main]]
# name = "Wedding ring configurator"
# url = "#cta"
# weight = 4
# 
# [[Languages.en.menu.main]]
# name = "Contact"
# url = "#contact"
# weight = 5

# [[Languages.en.menu.policy]]
# name = "Privacy Policy"
# url = "/datenschutz"
# weight = 60
# 
# [[Languages.en.menu.policy]]
# name = "Impressum"
# url = "/impressum"
# weight = 70

############################# Default Parameters ##########################
[params]
logo = "images/thumbnail_metallglanz.png.webp"
# Meta data
description = "Goldschmiede Goldspecht"
author = "Tabea Specht"
# Google Analytics
google_analytics_id = "" # Your ID
# post share
post_share = false

# preloader
[params.preloader]
enable = false
preloader = "images/thumbnail_metallglanz.png.webp"

# cookies
[params.cookies]
enable = false
expire_days = 2

############################# social icons ##########################
[[params.social]]
icon = "ti-instagram"                           # themify icon pack : https://themify.me/themify-icons
link = "https://www.instagram.com/gold_specht/"
[[params.social]]
icon = "ti-email"                      # themify icon pack : https://themify.me/themify-icons
link = "mailto:kontakt@gold-specht.de"


################################ German Language ########################
[Languages.de]
languageName = "De"
languageCode = "de-de"
contentDir = "content/de"
weight = 1
home = "Home"
copyright = "Copyright &copy; 2024 Goldschmiede Goldspecht"

################################ English Language ########################
# [Languages.en]
# languageName = "En"
# languageCode = "en-us"
# contentDir = "content/en"
# weight = 1
# home = "Home"
# copyright = "Copyright &copy; 2024 Goldschmiede Metallglanz"
