---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: data/de/index.yml
  label: Index
- type: document
  path: data/de/banner.yml
  label: Titel-Seite
- type: document
  path: data/de/feature.yml
  label: Über mich
- type: document
  path: data/de/service.yml
  label: Leistungen
- type: document
  path: data/de/portfolio.yml
  label: Galerie
- type: directory
  path: content/de/blog
  label: Blog
  create: all
  match: "**/*"
- type: document
  path: data/de/funfacts.yml
  label: Fun Facts
- type: document
  path: data/de/testimonial.yml
  label: Kunden Rezensionen
- type: document
  path: data/de/cta.yml
  label: Trauringkonfigurator
- type: document
  path: data/de/contact.yml
  label: Kontakt
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
